version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 961467505544.dkr.ecr.us-east-1.amazonaws.com/mssql-demo:latest
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 961467505544.dkr.ecr.us-east-1.amazonaws.com/mssql-demo:latest
  post_build:
    commands:
      - docker push 961467505544.dkr.ecr.us-east-1.amazonaws.com/mssql-demo:latest
      - printf '[{"name":"HelloWorld","imageUri":"%s"}]' 961467505544.dkr.ecr.us-east-1.amazonaws.com/mssql-demo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
